config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check 
  resources :mentoras

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mentora.rb
class Mentora < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mentoras_controller.rb
class MentorasController < ApplicationController
  def index 
    @mentoras = Mentora.all
  end

  def show
    @mentora = Mentora.find(params[:id])
  end

  def new 
    @mentora = Mentora.new
  end

  def create 
    @mentora = Mentora.new(mentora_params)
    @mentora.save
    redirect_to mentoras_path
  end

  def destroy
    @mentora = Mentora.find(params[:id])
    @mentora.destroy
    redirect_to mentoras_path
  end

  def edit
    @mentora = Mentora.find(params[:id])
  end

  def update
    @mentora = Mentora.find(params[:id])
    @mentora.update(mentora_params)
    redirect_to mentoras_path
  end

  private

  def mentora_params
    params.require(:mentora).permit(:nome, :email, :habilidades)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentoras_helper.rb
module MentorasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadastroMentora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mentoras/edit.html.erb
<h2>Editar</h2>
  <%= form_with(model: @mentora, local: true) do |form| %>
    <div>
      <%= form.label :nome, "Nome" %>
      <%= form.text_field :nome %>
    </div>
    
    <div>
      <%= form.label :email, "email" %>
      <%= form.text_field :email %>
    </div>
    <div>
      <%= form.label :habilidades, "habilidades" %>
      <%= form.text_field :habilidades %>
    </div>
    <div>
      <%= form.submit "Salvar" %>
    </div>
  <% end %>

app/views/mentoras/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'index', media: 'all' %>
  </head>

  <h1> Mentoras </h1>
  <%= link_to "Adicionar mentora", new_mentora_path, class: "button" %>
  <br>
  <br>
  <% @mentoras.each do |mentora| %>

    <%= link_to mentora.nome, mentora_path(mentora), class: "linkNome" %>
    <%= link_to "Visualizar", mentora_path(mentora),  class: "buttonLista" %>
    <%= link_to "Editar", edit_mentora_path(mentora),  class: "buttonLista" %>
    <%= link_to "Remover", mentora_path(mentora),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?" },  class: "buttonLista" %>
    <hr>

  <% end %>

</html>

app/views/mentoras/new.html.erb
<h2>Adicionar uma Mentora</h2>
  <%= form_with(model: @mentora, local: true) do |form| %>
    <div>
      <%= form.label :nome, "Nome" %>
      <%= form.text_field :nome %>
    </div>
    
    <div>
      <%= form.label :email, "email" %>
      <%= form.text_field :email %>
    </div>
    <div>
      <%= form.label :habilidades, "habilidades" %>
      <%= form.text_field :habilidades %>
    </div>
    <div>
      <%= form.submit "Add mentora" %>
    </div>
  <% end %>

app/views/mentoras/show.html.erb
<h3>Nome: </h3> 
<%= @mentora.nome %>
<hr>
<h3>Email: </h3> 
<%= @mentora.email %>
<hr>
<h3>Habilidades: </h3> 
<%= @mentora.habilidades %>
<hr>
<%= link_to "Editar", edit_mentora_path(@mentora) %>
<%= link_to "Remover", mentora_path(@mentora),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= link_to "Voltar", mentoras_path %>